version: 0.1

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - '**/*'
